//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutions.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerComment
    {
        public AnswerComment()
        {
            this.AnswerRecomments = new HashSet<AnswerRecomment>();
        }
    
        public int AnswerCommentCode { get; set; }
        public int AnswerCode { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual ICollection<AnswerRecomment> AnswerRecomments { get; set; }
    }
}
