//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutions.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseComment
    {
        public CaseComment()
        {
            this.CaseRecomment = new HashSet<CaseRecomment>();
        }
    
        public int CaseCommentCode { get; set; }
        public int CaseCode { get; set; }
        public int CommentUserCode { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual ICollection<CaseRecomment> CaseRecomment { get; set; }
    }
}
