//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutions.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Case = new HashSet<Case>();
        }
    
        public int CategoryCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Case> Case { get; set; }
    }
}
