//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutions.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SolutionsEntities3 : DbContext
    {
        public SolutionsEntities3()
            : base("name=SolutionsEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answer { get; set; }
        public DbSet<AnswerComment> AnswerComment { get; set; }
        public DbSet<AnswerRecomment> AnswerRecomment { get; set; }
        public DbSet<Block> Block { get; set; }
        public DbSet<Case> Case { get; set; }
        public DbSet<CaseComment> CaseComment { get; set; }
        public DbSet<CaseImage> CaseImage { get; set; }
        public DbSet<CaseRecomment> CaseRecomment { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Feedback> Feedback { get; set; }
        public DbSet<Follow> Follow { get; set; }
        public DbSet<Notification> Notification { get; set; }
        public DbSet<NotificationType> NotificationType { get; set; }
        public DbSet<Privacy> Privacy { get; set; }
        public DbSet<SatisfactoryLevel> SatisfactoryLevel { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Vote> Vote { get; set; }
        public DbSet<VoteType> VoteType { get; set; }
    }
}
